export const TYPE_COLORS = {
  normal: "bg-type-solid-normal",
  fire: "bg-type-solid-fire",
  water: "bg-type-solid-water",
  electric: "bg-type-solid-electric",
  grass: "bg-type-solid-grass",
  ice: "bg-type-solid-ice",
  fighting: "bg-type-solid-fighting",
  poison: "bg-type-solid-poison",
  ground: "bg-type-solid-ground",
  flying: "bg-type-solid-flying",
  psychic: "bg-type-solid-psychic",
  bug: "bg-type-solid-bug",
  rock: "bg-type-solid-rock",
  ghost: "bg-type-solid-ghost",
  dragon: "bg-type-solid-dragon",
  dark: "bg-type-solid-dark",
  steel: "bg-type-solid-steel",
  fairy: "bg-type-solid-fairy",
};

export const GRADIENT_CLASSES = {
  normal: "from-type-gradient-normal to-type-gradient-normal",
  fire: "from-type-gradient-fire to-type-gradient-fire",
  water: "from-type-gradient-water to-type-gradient-water",
  electric: "from-type-gradient-electric to-type-gradient-electric",
  grass: "from-type-gradient-grass to-type-gradient-grass",
  ice: "from-type-gradient-ice to-type-gradient-ice",
  fighting: "from-type-gradient-fighting to-type-gradient-fighting",
  poison: "from-type-gradient-poison to-type-gradient-poison",
  ground: "from-type-gradient-ground to-type-gradient-ground",
  flying: "from-type-gradient-flying to-type-gradient-flying",
  psychic: "from-type-gradient-psychic to-type-gradient-psychic",
  bug: "from-type-gradient-bug to-type-gradient-bug",
  rock: "from-type-gradient-rock to-type-gradient-rock",
  ghost: "from-type-gradient-ghost to-type-gradient-ghost",
  dragon: "from-type-gradient-dragon to-type-gradient-dragon",
  dark: "from-type-gradient-dark to-type-gradient-dark",
  steel: "from-type-gradient-steel to-type-gradient-steel",
  fairy: "from-type-gradient-fairy to-type-gradient-fairy",
};
